name: Dev Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        run: npm install

      - name: Run dev server check (optional)
        run: npm run dev
        continue-on-error: true  # Avoids breaking workflow if dev script hangs

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install client dependencies
        run: npm install

      - name: Build client
        run: npm run build

  deploy-to-render:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
